FROM indexyz/php
LABEL maintainer="Indexyz <indexyz@protonmail.com>"

ADD ./panel /var/www
COPY ./composer.json /var/www
WORKDIR /var/www

RUN bash | curl -SL https://getcomposer.org/installer -O composer.phar && \
    php composer.phar && \
    php composer.phar install
RUN bash | chmod 755 -R *
COPY ./docker-entrypoint.sh /docker-entrypoint.sh  

CMD ["/docker-entrypoint.sh"]
